my_list = [1, 2, 3, 4, 5]
res = (i**2 for i in my_list)  # generator expression and returns a iterator object. 
print(res)  # This will print the generator object, not the values

my_set = {1, 2, 3, 4, 5,1,2,3,4,5}
res2 = (i for i in my_set if i % 2 == 0)  # generator expression
print(list(res2))  # This will print the generator object, not the values

#yield is a keyword in python that is used to create a generator function. A generator function is a function that returns an iterator object. 
    # The yield statement is used to return a value from the generator function and pause the execution of the function. When the next() 
    # method is called on the iterator object, the execution of the generator function resumes from where it left off and continues until 
    # it reaches another yield statement or the end of the function.
#list comprehension use [] and generator expression use () and set comprehension use {} 
#list generator expression use () and set comprehension use {}
#generator expression is more memory efficient than list comprehension because it generates values on the fly and does not store them in memory.
#generator print(list(res))  # This will print the values generated by the generator expression
#print(res2)  # This will print the generator object, not the values

def countdown(n):
    while n > 0:
        yield n
        n -= 1  
countdown_gen = countdown(5)
for num in countdown_gen:
    print(num)  # This will print the values generated by the countdown generator function  